import type { Metadata } from 'next'
import { SessionProvider } from "next-auth/react"
import { Inter } from 'next/font/google'
import { Providers } from './providers'
import './globals.css'
import Navbar from './components/NavBar'
import Chatbot from './components/Chatbot'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Trackie',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Providers>
          <div className=''>
            {children}
          </div>
          <Chatbot></Chatbot>
        </Providers>
      </body>
    </html>
  )
}
